server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: locahost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.88.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /vh1
    listener:
      simple:
        prefetch: 1
        concurrency: 4
        acknowledge-mode: manual


feign:
  sentinel:
    enabled: true
