server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: locahost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.88.128
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.128:3306/guli_cart
    username: root
    password: root
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: F:\ShangGuigu\IdeaWorkSpace\gulimall\rsa\rsa.pub
    cookieName: GMALL-TOKEN
