server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: locahost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    priKeyPath: F:\ShangGuigu\IdeaWorkSpace\gulimall\rsa\rsa.pri
    pubKeyPath: F:\ShangGuigu\IdeaWorkSpace\gulimall\rsa\rsa.pub
    secret: 192JinZhengSen@1550506827@qqcom
    expire: 180
    cookieName: GMALL-TOKEN
    unick: unick

